# Generated by Django 2.2 on 2019-05-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='S_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=200)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocheck.F_name')),
            ],
        ),
    ]
